services:
  # 1. Define the Spring Boot Web Service
  - type: web
    name: nexus-gaming-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "8080"

      # Fixed Cloud Database Properties
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://://aivencloud.com
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

      # Fixed Twitch API Access
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: TWITCH_URL
        value: https://id.twitch.tv/oauth2/token
      - key: TWITCH_API_URL
        value: https://igdb.com

      # Security System Identity
      - key: APP_USERNAME
        value: bailey
      - key: APP_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
