spring.application.name=nexus-gaming-api
spring.jpa.hibernate.ddl-auto=update

# Twitch API Configuration
# Never hard code your credentials into the program because once it's put onto Github it will be stolen
twitch.client.id=${TWITCH_CLIENT_ID}
twitch.client.secret=${TWITCH_CLIENT_SECRET}
twitch.url=${TWITCH_URL}
twitch.api.url=${TWITCH_API_URL}
# These tell spring boot to look for the values in computers settings

# Variables for the database
spring.datasource.url=jdbc:mysql://mysqldb:3306/nexus_gaming
