spring.application.name=nexus-gaming-api
spring.jpa.hibernate.ddl-auto=update

# Database Routing - Uses the single URL if present on Render, otherwise builds the local layout
spring.datasource.url=jdbc:mysql://://aivencloud.com
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Twitch API Configuration - Maps to your active environmental variables
twitch.client.id=${TWITCH_CLIENT_ID}
twitch.client.secret=${TWITCH_CLIENT_SECRET}
twitch.url=${TWITCH_URL}
twitch.api.url=${TWITCH_API_URL}

# Authentication Architecture Hook
jwt.secret=${JWT_SECRET_KEY}

# Information for login to application for security
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

server.port=${PORT:8080}
server.address=0.0.0.0
