spring.application.name=nexus-gaming-api

# 1. Change update to none to stop Hibernate from running structural checks at boot
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# 2. Changed hardcoded text to an abstract environment placeholder variable
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Twitch API Configuration - Maps to your active environmental variables
twitch.client.id=${TWITCH_CLIENT_ID}
twitch.client.secret=${TWITCH_CLIENT_SECRET}
twitch.url=${TWITCH_URL}
twitch.api.url=${TWITCH_API_URL}

# Authentication Architecture Hook
jwt.secret=${JWT_SECRET_KEY}

# Information for login to application for security
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

# Port values
server.port=${PORT:8080}
server.address=0.0.0.0